### ISSUE TITLE
Update to use /student/dashbord/ backend route 

### ISSUE THREAD

**Issue by YoganshSharma** [kossiitkgp/KWoC-Frontend#121]
Following changes are required to be done
- Change request type to GET
- `username` field is not required in the request
- Fields like `evals` have been changed [refer](https://github.com/kossiitkgp/KWoC-Backend/blob/c93752a71e7e37450486ff99e8fff298b7bfedd4/controllers/student.go#L31C1-L45C2)
-  Endpoint /stats/student/{student_username} not required on the frontend use data received from /student/dashboard/
[Refer this](https://github.com/kossiitkgp/KWoC-Backend/blob/c93752a71e7e37450486ff99e8fff298b7bfedd4/controllers/student.go#L210)

**Comment by harshkhandeparkar** [comment]
Truth is being redefined.
