### ISSUE TITLE
Projects filter by tags not working

### ISSUE THREAD

**Issue by rajivharlalka** [kossiitkgp/KWoC-Frontend#62]
Projects not getting filtered by tags 
![image](https://user-images.githubusercontent.com/68731551/143683959-ae74fd2e-a73a-45e3-b113-0ba4db2b4c3a.png)

**Comment by harshkhandeparkar** [comment]
Working
![image](https://github.com/kossiitkgp/KWoC-Frontend/assets/34770591/67e76d2f-8daa-4d78-8ec7-e028646d5c8e)
