### ISSUE TITLE
Handle OAuth Errors

### ISSUE THREAD

**Issue by proffapt** [kossiitkgp/KWoC-Frontend#95]
#### Steps to Reproduce:

1. Click on either `Student Registration` or `Mentor Registration`.
2. Deny access to kwoc-2022 to your GitHub, will receive an error and the page will show this

<img width="1463" alt="image" src="https://user-images.githubusercontent.com/86282911/202888375-1b6f282b-ebd5-42fd-bdb7-12de87dfd6d3.png">

Link with the error query: https://kwoc.kossiitkgp.org/oauth/?error=access_denied&error_description=The+user+has+denied+your+application+access.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23access-denied&state=mentor

**Comment by harshkhandeparkar** [comment]
Truth is being redefined.
